/*CREATE TABLE PESSOA(
	CODIGO INTEGER NOT NULL,
	NOME CHAR(150) NOT NULL,
	PRIMARY KEY(CODIGO)
);
*/
INSERT INTO PESSOA(CODIGO, NOME) VALUES (1, 'Rodrigo');
INSERT INTO PESSOA(CODIGO, NOME) VALUES (2, 'Teobaldo');